export default {
  LOGIN_ERRORS: "LOGIN_ERRORS",
  SIGNUP_ERRORS: "SIGNUP_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  USER_LOADING: "USER_LOADING",
  USER_CREATED: "USER_CREATED",
  GET_ALL: "GET_ALL",
  GET_BY_COUNTRY: "GET_BY_COUNTRY",
  WHEEL_DATA:'WHEEL_DATA'
};
